version: "3.7"

services:
  appsmith-rts:
    restart: always
    container_name: appsmith-rts
    env_file: ./app/rts/.env
    build:
      context: ./app
      dockerfile: ./rts/Dockerfile
    networks:
      - appsmith
  appsmith-client:
    restart: always
    container_name: appsmith-client
    build:
      context: ./app
      dockerfile: ./client/Dockerfile
    ports:
      - "80:80"
    networks:
      - appsmith
    depends_on:
      - appsmith-internal-server
  appsmith-internal-server:
    restart: always
    container_name: appsmith-internal-server
    build:
      context: ./app/server
      dockerfile: ./Dockerfile
    env_file: ./app/server/envs/docker.env
    environment:
      APPSMITH_REDIS_URL: "redis://redis:6379"
      APPSMITH_MONGODB_URI: "mongodb://mongo:27017/appsmith"
    ports:
      - "8080:8080"
    depends_on:
      - mongosetup
      - redis
      - appsmith-rts
    networks:
      - appsmith
    volumes:
      - /var/lib/docker/volumes/appsmith-volumes/git-storage:/data/git-storage

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=appsmith
    volumes:
      - /var/lib/docker/volumes/appsmith-volumes/mongo:/data/db
    networks:
      - appsmith
    command: ["--replSet", "rs0", "--bind_ip_all"]


  mongosetup:
    image: mongo:4.4.6
    depends_on:
      - mongo
    restart: "no"
    volumes:
      - ./scripts/mongodb:/scripts
    networks:
      - appsmith
    entrypoint: [ "bash", "-c", "sh /scripts/init-mongo.sh"]

  redis:
    restart: always
    image: redis
    networks:
      - appsmith

networks:
  appsmith:
    driver: bridge